name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Valid Step
        run: echo "This is a valid step"
        
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: All the Tests and Coverage check
        run: mvn -X clean install

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t arunrameshdoc/demojava:1.0.0 .

      - name: Push Docker image
        run: docker push arunrameshdoc/demojava:1.0.0

      # - name: Run Java Application
      #   run: mvn spring-boot:run

      # - name: Build with Maven
      #   run: mvn --batch-mode --update-snapshots package

      # - name: Start Spring Boot Application
      #   run: java -jar target/springboot-demo-hello-world-0.0.1-SNAPSHOT.jar & echo $! > app.pid
        
     # - name: Stop Spring Boot Application
      #  run: |
        #  kill -TERM $(cat app.pid)
        #  rm app.pid

     # - name: Fetch secret from external service
      #  env:
       #   SECRET_VALUE: ${{ secrets.PLATFORM }}
      #  run: |
          # Fetch the secret from an external service
          # Use the SECRET_VALUE in your workflow
      #    echo "The secret is $SECRET_VALUE"


     # - name: Checkout code
       # uses: actions/checkout@v2

    #  - name: Use the GitHub Token to access another repository
     #   env:
     #     GITHUB_TOKEN: ${{ secrets.testlearn }}
     #   run: |
          # Use the GITHUB_TOKEN to clone the other repository or perform other actions
          # git clone https://github.com/helloworld.git
      #    echo "The Git ${{secrets.PLATFORM}}"

