name: Deploy Java App to Minikube with Docker Hub and Terraform github

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: arunrameshdoc/my-java-app:latest  # Replace with your Docker Hub username and image name

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Build the Java project
      run: ./mvnw clean package  # Build the Java application

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Store Docker Hub credentials in GitHub secrets
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image to Docker Hub
      run: |
        docker build -t $DOCKER_IMAGE .
        docker push $DOCKER_IMAGE

    - name: Set up Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        minikube start --driver=docker

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      working-directory: ./terraform
      run: terraform init

    - name: Apply Terraform configuration to Minikube
      working-directory: ./terraform
      run: terraform apply -auto-approve

    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get svc
