name: Use Secrets

on:
  push:
    branches:
      - main

jobs:
  use-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Secrets
        uses: actions/setup-node@v3
        with:
          run: |
            curl -sSL "https://raw.githubusercontent.com/your-org/secrets-repo/main/secrets" >> $GITHUB_ENV
            

      - name: Use Secrets
        run: echo "Using secret:$SECRET_KEY"
